revision_check_duration: 10 // in minutes

aws:
  accessKey: YOUR_AWS_ACCESS_KEY
  secretKey: YOUR_AWS_SECRET_KEY
  bucket: YOUR_AWS_DEPLOYMENT_BUCKET
  region: YOUR_AWS_REGION

deployments:

- application: staging.example.com
  environment: staging
  destination: /var/www/html/staging.example.com
  s3_revision_file: example.com/staging.tar.gz

- application: www.example.com
  environment: production
  destination: /var/www/html/www.example.com
  s3_revision_file: example.com/prod.tar.gz